services:
  web:
    build: .
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trader.rule=Host(`trader.kachestvobiz-ai.ru`)"
      - "traefik.http.routers.trader.entryPoints=websecure"
      - "traefik.http.routers.trader.tls.certResolver=letsencrypt"
      - "traefik.http.services.trader.loadbalancer.server.port=3000"
      - "traefik.http.routers.trader-http.rule=Host(`trader.kachestvobiz-ai.ru`)"
      - "traefik.http.routers.trader-http.entryPoints=web"
      - "traefik.http.routers.trader-http.middlewares=redirect-to-https"

networks:
  dokploy-network:
    external: true
